<?php

use Illuminate\Foundation\Inspiring;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;

Artisan::command('inspire', function () {
    $this->comment(Inspiring::quote());
})->purpose('Display an inspiring quote');

Artisan::command('schema:export-sqlite {--path=database/schema.sql}', function () {
    $path = (string) $this->option('path');

    $pdo = DB::connection()->getPdo();
    $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);
    if ($driver !== 'sqlite') {
        $this->error('This command only supports sqlite connections.');
        return self::FAILURE;
    }

    $rows = $pdo->query(
        "SELECT sql FROM sqlite_master WHERE sql IS NOT NULL AND type IN ('table','index','trigger','view') ORDER BY type, name"
    );

    $sql = "-- SQLite schema snapshot (local dev only).\n";
    $sql .= "-- For production MySQL, use DB_CONNECTION=mysql + `php artisan migrate` and optionally `php artisan schema:export-mysql`.\n\n";
    foreach ($rows as $row) {
        $stmt = (string) ($row['sql'] ?? '');
        $stmt = trim($stmt);
        if ($stmt === '') {
            continue;
        }
        $sql .= $stmt . ";\n\n";
    }

    $absolute = base_path($path);
    $dir = dirname($absolute);
    if (!is_dir($dir)) {
        mkdir($dir, 0777, true);
    }

    file_put_contents($absolute, $sql);
    $this->info("Wrote: {$path}");

    return self::SUCCESS;
})->purpose('Export sqlite schema to SQL file (no sqlite3 CLI)');

Artisan::command('schema:export-mysql {--path=database/schema.mysql.sql}', function () {
    $path = (string) $this->option('path');

    $connection = DB::connection();
    $pdo = $connection->getPdo();
    $driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);
    if ($driver !== 'mysql') {
        $this->error('This command requires DB_CONNECTION=mysql and a working MySQL connection.');

        return self::FAILURE;
    }

    $database = $connection->getDatabaseName();
    if ($database === '') {
        $this->error('Could not resolve database name from config.');

        return self::FAILURE;
    }

    $tables = $connection->select(
        'SELECT TABLE_NAME AS name FROM information_schema.TABLES WHERE TABLE_SCHEMA = ? AND TABLE_TYPE = ? ORDER BY TABLE_NAME',
        [$database, 'BASE TABLE']
    );

    $sql = "-- MySQL schema dump (generated by artisan schema:export-mysql)\n";
    $sql .= "-- Database: {$database}\n";
    $sql .= "-- Run on a server with the same migrations applied, or use `php artisan migrate` instead of importing this file.\n\n";
    $sql .= "SET NAMES utf8mb4;\n";
    $sql .= "SET FOREIGN_KEY_CHECKS=0;\n\n";

    foreach ($tables as $row) {
        $table = (string) ($row->name ?? '');
        if ($table === '') {
            continue;
        }

        $quotedTable = '`'.str_replace('`', '``', $table).'`';
        $create = $connection->selectOne('SHOW CREATE TABLE '.$quotedTable);
        $createSql = $create->{'Create Table'} ?? $create->{'Create View'} ?? null;
        if (! is_string($createSql) || $createSql === '') {
            continue;
        }

        $sql .= "DROP TABLE IF EXISTS `".str_replace('`', '``', $table)."`;\n";
        $sql .= $createSql.";\n\n";
    }

    $sql .= "SET FOREIGN_KEY_CHECKS=1;\n";

    $absolute = base_path($path);
    $dir = dirname($absolute);
    if (! is_dir($dir)) {
        mkdir($dir, 0777, true);
    }

    file_put_contents($absolute, $sql);
    $this->info("Wrote: {$path}");

    return self::SUCCESS;
})->purpose('Export MySQL CREATE TABLE statements (no mysqldump CLI)');
